name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # 🔹 Build + testes
      - name: Build + Testes Unitários
        run: mvn clean install
        working-directory: marketplace

      # 🔹 Testes unitários
      - name: Executar Testes Unitários
        run: mvn test
        working-directory: marketplace

      # 🔹 Testes de arquitetura
      - name: Executar Testes de Arquitetura
        run: mvn test -Dtest=ArchitectureTest
        working-directory: marketplace
